spring:
  datasource:
    url: jdbc:mysql://<MYSQL_PRIVATE_IP>:3306/productdb?serverTimezone=UTC&useSSL=true
    username: adminuser@a3a-dev-mysql-flex
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
