spring:
  datasource:
    url: jdbc:mysql://a3a-dev-db-mysql-sample.mysql.database.azure.com:3306/a3a_db
    username: a3aadmin
    password: 'martin1004!@'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: A3A App
    description: 3-Tier Architecture Demo App
    version: 1.0.0
  company: "Martin"